// Generated by Wrangler by running `wrangler types`

interface Env {
	GOOGLE_MAPS_API_KEY: string;
	METEO_KEY: string;
	TURNSTILE_SECRET: string;
	r2_token: string;
	r2_secret: string;
	r2_acess_id: string;
	CF_ACCOUNT_ID: string;
	CF_TOKEN: string;
	swv3: R2Bucket;
	swv3_d1: D1Database;
	AI: Ai;
}
