// Generated by Wrangler on Thu Oct 31 2024 06:04:19 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	GOOGLE_MAPS_API_KEY: string;
	METEO_KEY: string;
	TURNSTILE_SECRET: string;
	r2_token: string;
	r2_secret: string;
	r2_acess_id: string;
	"swv3-bucket": R2Bucket;
}
