// Generated by Wrangler on Sun Nov 03 2024 01:26:41 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	GOOGLE_MAPS_API_KEY: string;
	METEO_KEY: string;
	TURNSTILE_SECRET: string;
	r2_token: string;
	r2_secret: string;
	r2_acess_id: string;
	swv3: R2Bucket;
	swv3_d1: D1Database;
}
