name = "swv3"
compatibility_date = "2024-10-31"
pages_build_output_dir = "./build/client"

 [[d1_databases]]
 binding = "swv3_d1"
 database_name = "swv3"
 database_id = "b62f193e-5951-48e3-aae3-55864466a950"
 migrations_dir = "drizzle/migrations"
